---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ocp-environment-preparation
spec:
  params:
    - name: package_name
    - name: index_image
  workspaces:
    - name: source
  steps:
    - name: add-index
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        echo "Adding custom index to ocp: $(params.index_image)"

    - name: install-operator
      image: quay.io/amisstea/operator-pipeline-tools:latest
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        echo "Installing operator to a cluster: $(params.package_name)"
