---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-artifacts
spec:
  params:
    - name: pyxis_api_key
    - name: pyxis_url
      default: https://catalog.redhat.com/api/containers
    - name: log_file
    - name: result_file
  results:
    - name: log_url
    - name: result_url
  workspaces:
    - name: source
  steps:
    - name: upload-test-logs
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        echo "Uploading testing logs $(params.log_file)"

        echo https://foo.com/logs/123 | tee $(results.log_url.path)

    - name: upload-test-results
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        echo "Uploading testing results $(params.result_file)"

        echo https://foo.com/results/123 | tee $(results.result_url.path)
